// <auto-generated />
namespace INMETRO.CIPP.INFRA.ENTITYFRAMEWORK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class NewColumnCDN_Tipo_Integracao : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NewColumnCDN_Tipo_Integracao));
        
        string IMigrationMetadata.Id
        {
            get { return "201803081327512_New-ColumnCDN_Tipo_Integracao"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
