// <auto-generated />
namespace INMETRO.CIPP.INFRA.ENTITYFRAMEWORK.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CorrecaoColumnResponsavelTec : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CorrecaoColumnResponsavelTec));
        
        string IMigrationMetadata.Id
        {
            get { return "201803051748223_Correcao Column Responsavel Tec"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
