using INMETRO.CIPP.DOMINIO.Modelos;
using System.Data.Entity.Migrations;

namespace INMETRO.CIPP.INFRA.ENTITYFRAMEWORK.Migrations
{
   
    internal sealed class Configuration : DbMigrationsConfiguration<CippContexto>

    {
        public Configuration()
        {
            AutomaticMigrationsEnabled = false;
        }

        protected override void Seed(CippContexto context)
        {
            #region Organismos
            //context.Organismos.AddOrUpdate(
            //    x => x.Id,
            //    new Organismo() { CodigoOIA = "0016", Nome = "QUALITY INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0082", Nome = "TRANSTECH IVESUR BRASIL LTDA." },
            //    new Organismo() { CodigoOIA = "0112", Nome = "Tiririca Inspeção e Segurança Veicular Ltda" },
            //    new Organismo() { CodigoOIA = "0142", Nome = "Inscape Inspeções Ltda" },
            //    new Organismo() { CodigoOIA = "0224", Nome = "Tecsul Inspeção Veicular Ltda." },
            //    new Organismo() { CodigoOIA = "0257", Nome = "ITTRAN - Instituto Tecnológico de Transporte Ltda." },
            //    new Organismo() { CodigoOIA = "0269", Nome = "CENTRAL PORTO ALEGRE DE INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0279", Nome = "NACIONAL INSPEÇÕES LTDA." },
            //    new Organismo() { CodigoOIA = "0289", Nome = "EMBRAVEC - EMPRESA BRASILEIRA DE INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0294", Nome = "WEST ENGENHARIA DE INSPEÇÃO LTDA." },
            //    new Organismo() { CodigoOIA = "0307", Nome = "SBI-RS - INSPEÇÕES DE TANQUES E RESERVATÓRIOS LTDA." },
            //    new Organismo() { CodigoOIA = "0319", Nome = "SBI - SERRANA INSPEÇÕES DE PRODUTOS PERIGOSOS LTDA." },
            //    new Organismo() { CodigoOIA = "0322", Nome = "BBI SERVIÇOS DE INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0328", Nome = "INSPECENTRO INSPEÇÃO VEICULAR EIRELI - ME." },
            //    new Organismo() { CodigoOIA = "0351", Nome = "ITESV - Instituto Tecnologia de Engenharia e Segurança Veicular Ltda." },
            //    new Organismo() { CodigoOIA = "0368", Nome = "BUREAU BRASILEIRO DE INSPEÇÃO LTDA" },
            //    new Organismo() { CodigoOIA = "0420", Nome = "ATIVE OURINHOS INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0424", Nome = "IVECAR CENTRO INSPEÇÃO VEICULAR LTDA.	" },
            //    new Organismo() { CodigoOIA = "0426", Nome = "SINTEV - Sistema de Inspeção Técnica Veicular Ltda" },
            //    new Organismo() { CodigoOIA = "0427", Nome = "GCL - INSPEÇÕES VEICULAR LTDA" },
            //    new Organismo() { CodigoOIA = "0430", Nome = "CTV - Centro de Tecnologia Veicular Ltda." },
            //    new Organismo() { CodigoOIA = "0431", Nome = "Monitor Engenharia - Inspeção Técnica de Veículos Ltda" },
            //    new Organismo() { CodigoOIA = "0434", Nome = "TRIVELATO & QUEIROZ INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0439", Nome = "Nível Inspeções Ltda." },
            //    new Organismo() { CodigoOIA = "0440", Nome = "FIT INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0443", Nome = "AVAL SOROCABA INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0450", Nome = "CPI Veicular Ltda" },
            //    new Organismo() { CodigoOIA = "0455", Nome = " POTIGUAR INSPEÇÕES DE SEGURANÇA VEICULAR LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0463", Nome = "CBI - Centro Brasileiro de Inspeção Veicular Ltda. - EPP." },
            //    new Organismo() { CodigoOIA = "0465", Nome = "LAUDOCENTER INSPEÇÃO VEICULAR LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0467", Nome = "FIT INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0469", Nome = "CARDOSO DE PAULA VISTORIA DE SEGURANÇA AUTOMOBILISTICA LTDA" },
            //    new Organismo() { CodigoOIA = "0471", Nome = "MARTINS & CAETANO INSPEÇÕES VEICULARES LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0474", Nome = "GOIÂNIA INSPEÇÕES LTDA" },
            //    new Organismo() { CodigoOIA = "0476", Nome = "NATAN - CAPACITAÇÃO PARA TRANSPORTE DE PRODUTOS PERIGOSOS LTDA - ME." },
            //    new Organismo() { CodigoOIA = "0479", Nome = "INSPECIONAR - INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0481", Nome = "Ita Center Inspeção Veicular Ltda." },
            //    new Organismo() { CodigoOIA = "0482", Nome = "VITRAN ENGENHARIA LTDA - ME" },
            //    new Organismo() { CodigoOIA = "0485", Nome = "EIVA INSPEÇÃO VEICULAR LTDA" },
            //    new Organismo() { CodigoOIA = "0493", Nome = "INSPECENTRO INSPEÇÃO VEICULAR EIRELI - ME." },
            //    new Organismo() { CodigoOIA = "0498", Nome = "SIMON INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0501", Nome = "Tecmetro Inspeções Juiz de Fora Ltda" },
            //    new Organismo() { CodigoOIA = "0503", Nome = "VISTO-CAR PAULÍNIA INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0504", Nome = "BRASIL MG INSPEÇÕES VEICULARES JF LTDA." },
            //    new Organismo() { CodigoOIA = "0506", Nome = "VISTO-CAR Piracicaba Centro de Inspeção Veicular Ltda" },
            //    new Organismo() { CodigoOIA = "0512", Nome = "ATIVE MARINGÁ INSPEÇÕES VEICULARES LTDA. - ME" },
            //    new Organismo() { CodigoOIA = "0516", Nome = "SETA INSTITUIÇÃO TECNICA DE INSPEÇÃO VEICULAR LTDA" },
            //    new Organismo() { CodigoOIA = "0518", Nome = "RAMAF INSPEÇÕES LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0523", Nome = "DE PAULA VILAS BOAS - VISTORIA DE SEGURANÇA AUTOMOBILISTICA LTDA" },
            //    new Organismo() { CodigoOIA = "0524", Nome = "ENTRO DE INSPEÇÃO VEICULAR DE ITABAIANA LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0525", Nome = "Nasa Inspeção Veicular Ltda" },
            //    new Organismo() { CodigoOIA = "0526", Nome = "CIAA - CENTRO INSPEÇÃO AUTOMOTIVA AMERICANA LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0530", Nome = "Costa Fernandes Inspeções Veiculares Ltda." },
            //    new Organismo() { CodigoOIA = "0531", Nome = "ADAR INSPEÇÃO VEICULAR E CARGAS PERIGOSAS LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0532", Nome = "JABOATÃO DESCONTAMINAÇÃO E INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0536", Nome = "NIVEL - NÚCLEO DE INSPEÇÕES VEICULARES LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0540", Nome = "LARISSA FIRMINO DA SILVA - EPP." },
            //    new Organismo() { CodigoOIA = "0542", Nome = "IVECAR CENTRO INSPEÇÃO VEICULAR LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0545", Nome = "PAES DE OLIVEIRA & GOMES LTDA" },
            //    new Organismo() { CodigoOIA = "0549", Nome = "CENTRAL CHAPECÓ DE INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0551", Nome = "Central Pelotas de Inspeções Veiculares Ltda" },
            //    new Organismo() { CodigoOIA = "0552", Nome = "ITAMETRO INSPEÇÕES VEICULARES - ME." },
            //    new Organismo() { CodigoOIA = "0554", Nome = "Atlantida Inspeção Veicular Ltda-EPP." },
            //    new Organismo() { CodigoOIA = "0556", Nome = "VISTEC - Vistoria Técnica Ltda" },
            //    new Organismo() { CodigoOIA = "0559", Nome = "Visto-Car São José Inspeção Veicular Ltda." },
            //    new Organismo() { CodigoOIA = "0562", Nome = "CETEM - Centro Tecnológico Mecânico Ltda." },
            //    new Organismo() { CodigoOIA = "0563", Nome = "ARTE REAL INSPEÇÃO VEICULAR LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0565", Nome = " SERITRAN - SERVIÇO DE INSPEÇÃO EM TRANSPORTES LTDA." },
            //    new Organismo() { CodigoOIA = "0568", Nome = "INSPETRO DE MACAÉ LTDA." },
            //    new Organismo() { CodigoOIA = "0569", Nome = "INSPEVEL - INSPEÇÃO VEICULAR DE CASCAVEL LTDA." },
            //    new Organismo() { CodigoOIA = "0570", Nome = "SETA INSTITUIÇÃO TÉCNICA DE INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0574", Nome = "VISTO-CAR ANCHIETA INSPEÇÃO VEICULAR LTDA. - EPP" },
            //    new Organismo() { CodigoOIA = "0575", Nome = "SETA REALENGO INSTITUIÇÃO TÉCNICA DE INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0576", Nome = "Inspeguará Inspeção Veicular Guarapuava Ltda." },
            //    new Organismo() { CodigoOIA = "0579", Nome = "ARAUCÁRIA INSPEÇÕES LTDA." },
            //    new Organismo() { CodigoOIA = "0583", Nome = "SINAU - SERVIÇO DE INSPEÇÃO AUTOMOTIVA LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0584", Nome = "SANTO ANDRÉ INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0586", Nome = "LIPP - LIMEIRA INSPEÇÕES LTDA." },
            //    new Organismo() { CodigoOIA = "0587", Nome = "GUARU INSPEÇÕES LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0588", Nome = "SEVEL - Segurança Veicular Paraná Ltda. - EPP." },
            //    new Organismo() { CodigoOIA = "0589", Nome = "JCP Inspeções Veiculares LTDA." },
            //    new Organismo() { CodigoOIA = "0590", Nome = "ARA PP INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0591", Nome = "GMAP INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0593", Nome = "ECV - EMPRESA CAPIXABA DE VISTORIAS LTDA." },
            //    new Organismo() { CodigoOIA = "0594", Nome = "CRIVE - CENTRO REG. DE INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0598", Nome = "ITV INSPEÇÃO TÉCNICA VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0601", Nome = "MAXY ENGENHARIA DE INSPEÇÃO LTDA." },
            //    new Organismo() { CodigoOIA = "0603", Nome = "IVETU INSPEÇÃO VEICULAR TUBARÃO LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0606", Nome = "INSPENORTE INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0610", Nome = "CASCAVEL INSPEÇÕES LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0611", Nome = "ITV - Inspeção Técnica Veicular Ltda." },
            //    new Organismo() { CodigoOIA = "0612", Nome = "CIAUTO - CENTRO DE INSPEÇÃO AUTOMOTIVA LTDA." },
            //    new Organismo() { CodigoOIA = "0613", Nome = "ETESUL PLANALTO INSPEÇÃO VEICULAR LTDA ME" },
            //    new Organismo() { CodigoOIA = "0614", Nome = "NECAVA - Inspeção e Pesquisa em Transporte Ltda. - ME." },
            //    new Organismo() { CodigoOIA = "0616", Nome = "DELTA SERVIÇOS INSPEÇÃO LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0622", Nome = "ECIV EMPRESA CRICIUMENSE DE INSPEÇÕES VEICULARES LTDA" },
            //    new Organismo() { CodigoOIA = "0623", Nome = "PANTANAL INSPEÇÕES LTDA ME" },
            //    new Organismo() { CodigoOIA = "0624", Nome = "CEI - CENTRO ESPECIALIZADO DE INSPEÇÕES LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0625", Nome = "MINAS INSPEÇÕES EM VEÍCULOS E EQUIPAMENTOS LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0627", Nome = "VISAVERO- Vistorias e Inspeções de Segurança e Ambiental em Veículos Rodoviários LTDA." },
            //    new Organismo() { CodigoOIA = "0628", Nome = "CIC - CENTRO DE INSPEÇÕES E CONSULTORIAS LTDA. EPP." },
            //    new Organismo() { CodigoOIA = "0630", Nome = "VIU VEICULAR INSPEÇÕES UBERLÂNDIA LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0631", Nome = "SERITRAM - SERVIÇO DE INSPEÇÃO EM TRANSPORTES DE MARABÁ LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0632", Nome = "PARANÁ INSPEÇÕES - EIRELLI - ME." },
            //    new Organismo() { CodigoOIA = "0633", Nome = "INSPESAN INSPEÇÕES MURIAÉ LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0634", Nome = "FÊNIX INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0635", Nome = "Central Santa Maria de Inspeções Veiculares Ltda. - EPP." },
            //    new Organismo() { CodigoOIA = "0636", Nome = "POLO CAPUAVA - INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0637", Nome = "CIVIC 1 - Inspeção Veicular EIRELI - EPP." },
            //    new Organismo() { CodigoOIA = "0640", Nome = "WEST ENGENHARIA DE INSPEÇÃO LTDA." },
            //    new Organismo() { CodigoOIA = "0641", Nome = "VITRAN ENGENHARIA LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0645", Nome = "WEST ENGENHARIA DE INSPEÇÃO LTDA. - FILIAL MARITUBA/PA" },
            //    new Organismo() { CodigoOIA = "0646", Nome = "WEST ENGENHARIA DE INSPEÇÃO LTDA. - GUARULHOS" },
            //    new Organismo() { CodigoOIA = "0647", Nome = "METROPOLITAN INSPEÇÕES LTDA - EPP" },
            //    new Organismo() { CodigoOIA = "0652", Nome = "MULT CEARÁ INSPEÇÃO LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0656", Nome = "Master Inspeções Veiculares Ltda - EPP" },
            //    new Organismo() { CodigoOIA = "0657", Nome = "SETA - REALENGO INSTITUIÇÃO TÉCNICA DE INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0659", Nome = "SETA NORTE TÉCNICA INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0663", Nome = "AVAL LONDRINA INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0665", Nome = "NIVEL NÚCLEO DE INSPEÇÕES VEICULARES DE ANÁPOLIS LTDA - ME" },
            //    new Organismo() { CodigoOIA = "0668", Nome = "BR VALE ENGENHARIA DE INSPEÇÃO LTDA." },
            //    new Organismo() { CodigoOIA = "0672", Nome = "BETIM INSPEÇÕES LTDA - ME" },
            //    new Organismo() { CodigoOIA = "0674", Nome = "LÍDER SUL INSPEÇÕES LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0676", Nome = "Paraiba Serviço de Inspeção Veicular Ltda - EPP" },
            //    new Organismo() { CodigoOIA = "0677", Nome = "CETEI - CENTRO TÉCNICO DE ENGENHARIA DE INSPEÇÃO LTDA." },
            //    new Organismo() { CodigoOIA = "0679", Nome = "CINSPEMAR - Centro Especializado de Inspeções do Maranhão Ltda. - ME." },
            //    new Organismo() { CodigoOIA = "0680", Nome = "SETA - Instituição Técnica de Inspeção Veicular Ltda. - EPP." },
            //    new Organismo() { CodigoOIA = "0684", Nome = "SHERLOCKAR INSPEÇÃO VEICULAR EIRELLI." },
            //    new Organismo() { CodigoOIA = "0687", Nome = "NORTEKAR - INSPEÇÃO VEICULAR LTDA EPP" },
            //    new Organismo() { CodigoOIA = "0689", Nome = "DCX Inspeçao e Engenharia Ltda" },
            //    new Organismo() { CodigoOIA = "0691", Nome = "CIAP CENTRO DE INSPEÇÃO AUTOMOTIVA PAULÍNIA LTDA" },
            //    new Organismo() { CodigoOIA = "0692", Nome = "Seta Instituição Técnica de Inspeção Veicular Ltda. - EPP." },
            //    new Organismo() { CodigoOIA = "0696", Nome = "ITAJAÍ INSPEÇÕES VEICULARES LTDA" },
            //    new Organismo() { CodigoOIA = "0698", Nome = "BUREAU ITAJAIENSE DE INSPEÇÃO VEICULAR LTDA - ME" },
            //    new Organismo() { CodigoOIA = "0699", Nome = "FIT INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0702", Nome = "MAYARA LETICIA BALESTERO. - ME." },
            //    new Organismo() { CodigoOIA = "0704", Nome = "SIVIC SEGURANÇA E INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0705", Nome = "MENDONÇA, MENDONÇA & SCHUNKE LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0706", Nome = "SETA SÃO LUÍS INSTITUIÇÃO TÉCNICA DE INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0712", Nome = "ATIVE PARANAGUÁ INSPEÇÕES VEICULARES LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0714", Nome = "Otimiza Inspeção Veicular Ltda. - EPP." },
            //    new Organismo() { CodigoOIA = "0716", Nome = "ESTAÇÃO INSPEÇÃO VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0722", Nome = "Núcleo de Inspeção Veicular Ltda. - ME." },
            //    new Organismo() { CodigoOIA = "0723", Nome = "PANTANAL INSPEÇÃO VEICULAR LTDA .- EPP." },
            //    new Organismo() { CodigoOIA = "0724", Nome = "CAIBI INSPEÇÕES VEICULARES LTDA." },
            //    new Organismo() { CodigoOIA = "0727", Nome = "CIVI - Centro de Inspeção Veicular de Arapiraca Ltda. - ME." },
            //    new Organismo() { CodigoOIA = "0731", Nome = "CONRADO E SILVA LTDA. - ME." },
            //    new Organismo() { CodigoOIA = "0734", Nome = "INSPECAMPO INSPEÇÃO DE SEGURANÇA VEICULAR DE CAMPO LARGO LTDA." },
            //    new Organismo() { CodigoOIA = "0735", Nome = "EJB - SERVIÇOS DE INSPEÇÃO TÉCNICA VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0738", Nome = "NOVA INSPEÇÃO VEICULAR LTDA. - EPP." },
            //    new Organismo() { CodigoOIA = "0740", Nome = "ISTO MAIS VISTORIA VEICULAR LTDA." },
            //    new Organismo() { CodigoOIA = "0742", Nome = "BR INSPEÇÃO TÉCNICA VEICULAR - ME." },
            //    new Organismo() { CodigoOIA = "0752", Nome = "JULIANA DE BRITO PEREIRA - ME." },
            //    new Organismo() { CodigoOIA = "0754", Nome = "Maringá Inspeção Veicular Ltda. - ME." },
            //    new Organismo() { CodigoOIA = "0755", Nome = "AFD INSPEÇÕES VEICULARES EIRELI - ME." },
            //     new Organismo() { CodigoOIA = "7777", Nome = "TEST ORGANISMO - 2", EhAtivo = true },
            //new Organismo() { CodigoOIA = "8888", Nome = "TEST ORGANISMO - 2", EhAtivo = true },
            //new Organismo() { CodigoOIA = "9999", Nome = "TEST ORGANISMO - 4", EhAtivo = true },
            //new Organismo() { CodigoOIA = "0001", Nome = "TESTE-ORGANISMO" });
            #endregion

            #region FtpInfo

            //context.IntegracaoInfo.AddOrUpdate(
            //    new FTPInfo()
            //    {
            //        OrganismoId = 2,
            //        HostURI = $"ftp://transtechmga.ddns.net:21/",
            //        Usuario = $"TRANSTECHLI03",
            //        Senha = $"000316",
            //        DiretorioInspecao = $"/Inspecoes/",
            //        DiretorioInspecaoLocal = $"82\\",
            //        DiretorioInspecaoRemoto = $"/New/"
            //    });
            //new FTPInfo() { OrganismoId = 156, HostURI = $"ftp://184.168.109.66:2112/", Usuario = $"nakoa_ftp", Senha = $"n@k@412!", DiretorioInspecao = $"/new-orders/", DiretorioInspecaoLocal = $"7777\\", DiretorioInspecaoRemoto = $"/New/" },
            //new FTPInfo() { OrganismoId = 157, HostURI = $"ftp://184.168.109.66:2111/", Usuario = $"cocomoon_ftp", Senha = $"c3e#22F!", DiretorioInspecao = $"/new-orders/", DiretorioInspecaoLocal = $"8888\\", DiretorioInspecaoRemoto = $"/New/" },
            //new FTPInfo() { OrganismoId = 158, HostURI = $"ftp://184.168.109.66:2111/", Usuario = $"cocomoon_ftp", Senha = $"c3e#22F!", DiretorioInspecao = $"/new-orders/", DiretorioInspecaoLocal = $"9999\\", DiretorioInspecaoRemoto = $"/New/" });

            #endregion


        }
    }
}
