//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INMETRO.CIPP.WEB.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://inmetro.gov.br/ControleAcesso/DataContracts")]
    [System.SerializableAttribute()]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private INMETRO.CIPP.WEB.ServiceReference1.Perfil[] PerfisField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private INMETRO.CIPP.WEB.ServiceReference1.PessoaFisica PessoaFisicaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NascimentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControleAtivoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private INMETRO.CIPP.WEB.ServiceReference1.TipoUsuario TipoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public INMETRO.CIPP.WEB.ServiceReference1.Perfil[] Perfis {
            get {
                return this.PerfisField;
            }
            set {
                if ((object.ReferenceEquals(this.PerfisField, value) != true)) {
                    this.PerfisField = value;
                    this.RaisePropertyChanged("Perfis");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public INMETRO.CIPP.WEB.ServiceReference1.PessoaFisica PessoaFisica {
            get {
                return this.PessoaFisicaField;
            }
            set {
                if ((object.ReferenceEquals(this.PessoaFisicaField, value) != true)) {
                    this.PessoaFisicaField = value;
                    this.RaisePropertyChanged("PessoaFisica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.DateTime Nascimento {
            get {
                return this.NascimentoField;
            }
            set {
                if ((this.NascimentoField.Equals(value) != true)) {
                    this.NascimentoField = value;
                    this.RaisePropertyChanged("Nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string ControleAtivo {
            get {
                return this.ControleAtivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ControleAtivoField, value) != true)) {
                    this.ControleAtivoField = value;
                    this.RaisePropertyChanged("ControleAtivo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public INMETRO.CIPP.WEB.ServiceReference1.TipoUsuario Tipo {
            get {
                return this.TipoField;
            }
            set {
                if ((this.TipoField.Equals(value) != true)) {
                    this.TipoField = value;
                    this.RaisePropertyChanged("Tipo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PessoaFisica", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class PessoaFisica : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CPFField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SexoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime NascimentoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CPF {
            get {
                return this.CPFField;
            }
            set {
                if ((object.ReferenceEquals(this.CPFField, value) != true)) {
                    this.CPFField = value;
                    this.RaisePropertyChanged("CPF");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((object.ReferenceEquals(this.SexoField, value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public System.DateTime Nascimento {
            get {
                return this.NascimentoField;
            }
            set {
                if ((this.NascimentoField.Equals(value) != true)) {
                    this.NascimentoField = value;
                    this.RaisePropertyChanged("Nascimento");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Perfil", Namespace="http://inmetro.gov.br/ControleAcesso/DataContracts")]
    [System.SerializableAttribute()]
    public partial class Perfil : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoSistemaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CodigoPerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomePerfilField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ControleAtivoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string CodigoSistema {
            get {
                return this.CodigoSistemaField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoSistemaField, value) != true)) {
                    this.CodigoSistemaField = value;
                    this.RaisePropertyChanged("CodigoSistema");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string CodigoPerfil {
            get {
                return this.CodigoPerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.CodigoPerfilField, value) != true)) {
                    this.CodigoPerfilField = value;
                    this.RaisePropertyChanged("CodigoPerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string NomePerfil {
            get {
                return this.NomePerfilField;
            }
            set {
                if ((object.ReferenceEquals(this.NomePerfilField, value) != true)) {
                    this.NomePerfilField = value;
                    this.RaisePropertyChanged("NomePerfil");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string ControleAtivo {
            get {
                return this.ControleAtivoField;
            }
            set {
                if ((object.ReferenceEquals(this.ControleAtivoField, value) != true)) {
                    this.ControleAtivoField = value;
                    this.RaisePropertyChanged("ControleAtivo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TipoUsuario", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
    public enum TipoUsuario : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Interno = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Externo = 1,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FiltroObterTodosUsuariosEnum", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
    public enum FiltroObterTodosUsuariosEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Todos = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Internos = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Externos = 2,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TokenInvalidoFault", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class TokenInvalidoFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TokenField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Token {
            get {
                return this.TokenField;
            }
            set {
                if ((object.ReferenceEquals(this.TokenField, value) != true)) {
                    this.TokenField = value;
                    this.RaisePropertyChanged("Token");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Login", Namespace="http://inmetro.gov.br/ControleAcesso/DataContracts")]
    [System.SerializableAttribute()]
    public partial class Login : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UserNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SenhaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string UserName {
            get {
                return this.UserNameField;
            }
            set {
                if ((object.ReferenceEquals(this.UserNameField, value) != true)) {
                    this.UserNameField = value;
                    this.RaisePropertyChanged("UserName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string Senha {
            get {
                return this.SenhaField;
            }
            set {
                if ((object.ReferenceEquals(this.SenhaField, value) != true)) {
                    this.SenhaField = value;
                    this.RaisePropertyChanged("Senha");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="RetornoVerificacaoServico", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.Elemento")]
    [System.SerializableAttribute()]
    public partial class RetornoVerificacaoServico : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ConsultaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EHashField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MensagemField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ScHashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Consulta {
            get {
                return this.ConsultaField;
            }
            set {
                if ((this.ConsultaField.Equals(value) != true)) {
                    this.ConsultaField = value;
                    this.RaisePropertyChanged("Consulta");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EHash {
            get {
                return this.EHashField;
            }
            set {
                if ((object.ReferenceEquals(this.EHashField, value) != true)) {
                    this.EHashField = value;
                    this.RaisePropertyChanged("EHash");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Mensagem {
            get {
                return this.MensagemField;
            }
            set {
                if ((object.ReferenceEquals(this.MensagemField, value) != true)) {
                    this.MensagemField = value;
                    this.RaisePropertyChanged("Mensagem");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ScHash {
            get {
                return this.ScHashField;
            }
            set {
                if ((object.ReferenceEquals(this.ScHashField, value) != true)) {
                    this.ScHashField = value;
                    this.RaisePropertyChanged("ScHash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UsuarioInexistenteFault", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
    [System.SerializableAttribute()]
    public partial class UsuarioInexistenteFault : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LoginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MessageField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Login {
            get {
                return this.LoginField;
            }
            set {
                if ((object.ReferenceEquals(this.LoginField, value) != true)) {
                    this.LoginField = value;
                    this.RaisePropertyChanged("Login");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Message {
            get {
                return this.MessageField;
            }
            set {
                if ((object.ReferenceEquals(this.MessageField, value) != true)) {
                    this.MessageField = value;
                    this.RaisePropertyChanged("Message");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://inmetro.gov.br/ControleAcesso", ConfigurationName="ServiceReference1.IAutenticacaoServico")]
    public interface IAutenticacaoServico {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/TodosUsuarios", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/TodosUsuariosResponse")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario[] TodosUsuarios(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/TodosUsuarios", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/TodosUsuariosResponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario[]> TodosUsuariosAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterUsuario", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterUsuarioResponse")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario ObterUsuario(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterUsuario", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterUsuarioResponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> ObterUsuarioAsync(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterTodosUsuarios", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterTodosUsuariosRespo" +
            "nse")]
        [System.ServiceModel.FaultContractAttribute(typeof(INMETRO.CIPP.WEB.ServiceReference1.TokenInvalidoFault), Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterTodosUsuariosToken" +
            "InvalidoFaultFault", Name="TokenInvalidoFault", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario[] ObterTodosUsuarios(string token, INMETRO.CIPP.WEB.ServiceReference1.FiltroObterTodosUsuariosEnum filtro, bool filtrarPorSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterTodosUsuarios", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterTodosUsuariosRespo" +
            "nse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario[]> ObterTodosUsuariosAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.FiltroObterTodosUsuariosEnum filtro, bool filtrarPorSistema);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuario", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioRespon" +
            "se")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario AutenticarUsuario(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuario", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioRespon" +
            "se")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarUsuarioAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioAnonim" +
            "o", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioAnonim" +
            "oResponse")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario AutenticarUsuarioAnonimo(string token, string credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioAnonim" +
            "o", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioAnonim" +
            "oResponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarUsuarioAnonimoAsync(string token, string credencial);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioExtern" +
            "o", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioExtern" +
            "oResponse")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario AutenticarUsuarioExterno(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioExtern" +
            "o", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarUsuarioExtern" +
            "oResponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarUsuarioExternoAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/Autenticar", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarResponse")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario Autenticar(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/Autenticar", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AutenticarResponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/SolicitarSenhaTemporari" +
            "a", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/SolicitarSenhaTemporari" +
            "aResponse")]
        void SolicitarSenhaTemporaria(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/SolicitarSenhaTemporari" +
            "a", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/SolicitarSenhaTemporari" +
            "aResponse")]
        System.Threading.Tasks.Task SolicitarSenhaTemporariaAsync(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtualizarPerfis", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtualizarPerfisResponse" +
            "")]
        void AtualizarPerfis(string token, string login, string[] perfis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtualizarPerfis", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtualizarPerfisResponse" +
            "")]
        System.Threading.Tasks.Task AtualizarPerfisAsync(string token, string login, string[] perfis);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AlterarSenhaUsuarioExte" +
            "rno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AlterarSenhaUsuarioExte" +
            "rnoResponse")]
        void AlterarSenhaUsuarioExterno(string token, string login, string senhaAtual, string novaSenha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AlterarSenhaUsuarioExte" +
            "rno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AlterarSenhaUsuarioExte" +
            "rnoResponse")]
        System.Threading.Tasks.Task AlterarSenhaUsuarioExternoAsync(string token, string login, string senhaAtual, string novaSenha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/PerfisSistema", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/PerfisSistemaResponse")]
        string[] PerfisSistema(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/PerfisSistema", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/PerfisSistemaResponse")]
        System.Threading.Tasks.Task<string[]> PerfisSistemaAsync(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterListaPerfisUsuario" +
            "Externo", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterListaPerfisUsuario" +
            "ExternoResponse")]
        string[] ObterListaPerfisUsuarioExterno(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterListaPerfisUsuario" +
            "Externo", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterListaPerfisUsuario" +
            "ExternoResponse")]
        System.Threading.Tasks.Task<string[]> ObterListaPerfisUsuarioExternoAsync(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/VerificacaoPeriodicaSer" +
            "vico", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/VerificacaoPeriodicaSer" +
            "vicoResponse")]
        INMETRO.CIPP.WEB.ServiceReference1.RetornoVerificacaoServico VerificacaoPeriodicaServico();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/VerificacaoPeriodicaSer" +
            "vico", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/VerificacaoPeriodicaSer" +
            "vicoResponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.RetornoVerificacaoServico> VerificacaoPeriodicaServicoAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuarioExterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuarioExternoResp" +
            "onse")]
        void CriarUsuarioExterno(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuarioExterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuarioExternoResp" +
            "onse")]
        System.Threading.Tasks.Task CriarUsuarioExternoAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuario", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuarioResponse")]
        void CriarUsuario(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuario", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/CriarUsuarioResponse")]
        System.Threading.Tasks.Task CriarUsuarioAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario, string senha);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AssociarUsuarioAoSistem" +
            "aPerfil", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AssociarUsuarioAoSistem" +
            "aPerfilResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(INMETRO.CIPP.WEB.ServiceReference1.UsuarioInexistenteFault), Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AssociarUsuarioAoSistem" +
            "aPerfilUsuarioInexistenteFaultFault", Name="UsuarioInexistenteFault", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
        [System.ServiceModel.FaultContractAttribute(typeof(INMETRO.CIPP.WEB.ServiceReference1.TokenInvalidoFault), Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AssociarUsuarioAoSistem" +
            "aPerfilTokenInvalidoFaultFault", Name="TokenInvalidoFault", Namespace="http://schemas.datacontract.org/2004/07/ControleAcessoService.DataContracts")]
        void AssociarUsuarioAoSistemaPerfil(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AssociarUsuarioAoSistem" +
            "aPerfil", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AssociarUsuarioAoSistem" +
            "aPerfilResponse")]
        System.Threading.Tasks.Task AssociarUsuarioAoSistemaPerfilAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/BuscarUsuarioExterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/BuscarUsuarioExternoRes" +
            "ponse")]
        INMETRO.CIPP.WEB.ServiceReference1.Usuario BuscarUsuarioExterno(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/BuscarUsuarioExterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/BuscarUsuarioExternoRes" +
            "ponse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> BuscarUsuarioExternoAsync(string token, string login);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioE" +
            "xterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioE" +
            "xternoResponse")]
        void AtivarDesativarUsuarioExterno(string token, string login, bool ativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioE" +
            "xterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioE" +
            "xternoResponse")]
        System.Threading.Tasks.Task AtivarDesativarUsuarioExternoAsync(string token, string login, bool ativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioI" +
            "nterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioI" +
            "nternoResponse")]
        void AtivarDesativarUsuarioInterno(string token, string login, bool ativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioI" +
            "nterno", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/AtivarDesativarUsuarioI" +
            "nternoResponse")]
        System.Threading.Tasks.Task AtivarDesativarUsuarioInternoAsync(string token, string login, bool ativo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterPerfisSistema", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterPerfisSistemaRespo" +
            "nse")]
        INMETRO.CIPP.WEB.ServiceReference1.Perfil[] ObterPerfisSistema(string token);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterPerfisSistema", ReplyAction="http://inmetro.gov.br/ControleAcesso/IAutenticacaoServico/ObterPerfisSistemaRespo" +
            "nse")]
        System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Perfil[]> ObterPerfisSistemaAsync(string token);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAutenticacaoServicoChannel : INMETRO.CIPP.WEB.ServiceReference1.IAutenticacaoServico, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AutenticacaoServicoClient : System.ServiceModel.ClientBase<INMETRO.CIPP.WEB.ServiceReference1.IAutenticacaoServico>, INMETRO.CIPP.WEB.ServiceReference1.IAutenticacaoServico {
        
        public AutenticacaoServicoClient() {
        }
        
        public AutenticacaoServicoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AutenticacaoServicoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacaoServicoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AutenticacaoServicoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario[] TodosUsuarios(string token) {
            return base.Channel.TodosUsuarios(token);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario[]> TodosUsuariosAsync(string token) {
            return base.Channel.TodosUsuariosAsync(token);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario ObterUsuario(string token, string login) {
            return base.Channel.ObterUsuario(token, login);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> ObterUsuarioAsync(string token, string login) {
            return base.Channel.ObterUsuarioAsync(token, login);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario[] ObterTodosUsuarios(string token, INMETRO.CIPP.WEB.ServiceReference1.FiltroObterTodosUsuariosEnum filtro, bool filtrarPorSistema) {
            return base.Channel.ObterTodosUsuarios(token, filtro, filtrarPorSistema);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario[]> ObterTodosUsuariosAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.FiltroObterTodosUsuariosEnum filtro, bool filtrarPorSistema) {
            return base.Channel.ObterTodosUsuariosAsync(token, filtro, filtrarPorSistema);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario AutenticarUsuario(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login) {
            return base.Channel.AutenticarUsuario(token, login);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarUsuarioAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login) {
            return base.Channel.AutenticarUsuarioAsync(token, login);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario AutenticarUsuarioAnonimo(string token, string credencial) {
            return base.Channel.AutenticarUsuarioAnonimo(token, credencial);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarUsuarioAnonimoAsync(string token, string credencial) {
            return base.Channel.AutenticarUsuarioAnonimoAsync(token, credencial);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario AutenticarUsuarioExterno(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login) {
            return base.Channel.AutenticarUsuarioExterno(token, login);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarUsuarioExternoAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login) {
            return base.Channel.AutenticarUsuarioExternoAsync(token, login);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario Autenticar(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login) {
            return base.Channel.Autenticar(token, login);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> AutenticarAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Login login) {
            return base.Channel.AutenticarAsync(token, login);
        }
        
        public void SolicitarSenhaTemporaria(string token, string login) {
            base.Channel.SolicitarSenhaTemporaria(token, login);
        }
        
        public System.Threading.Tasks.Task SolicitarSenhaTemporariaAsync(string token, string login) {
            return base.Channel.SolicitarSenhaTemporariaAsync(token, login);
        }
        
        public void AtualizarPerfis(string token, string login, string[] perfis) {
            base.Channel.AtualizarPerfis(token, login, perfis);
        }
        
        public System.Threading.Tasks.Task AtualizarPerfisAsync(string token, string login, string[] perfis) {
            return base.Channel.AtualizarPerfisAsync(token, login, perfis);
        }
        
        public void AlterarSenhaUsuarioExterno(string token, string login, string senhaAtual, string novaSenha) {
            base.Channel.AlterarSenhaUsuarioExterno(token, login, senhaAtual, novaSenha);
        }
        
        public System.Threading.Tasks.Task AlterarSenhaUsuarioExternoAsync(string token, string login, string senhaAtual, string novaSenha) {
            return base.Channel.AlterarSenhaUsuarioExternoAsync(token, login, senhaAtual, novaSenha);
        }
        
        public string[] PerfisSistema(string token) {
            return base.Channel.PerfisSistema(token);
        }
        
        public System.Threading.Tasks.Task<string[]> PerfisSistemaAsync(string token) {
            return base.Channel.PerfisSistemaAsync(token);
        }
        
        public string[] ObterListaPerfisUsuarioExterno(string token, string login) {
            return base.Channel.ObterListaPerfisUsuarioExterno(token, login);
        }
        
        public System.Threading.Tasks.Task<string[]> ObterListaPerfisUsuarioExternoAsync(string token, string login) {
            return base.Channel.ObterListaPerfisUsuarioExternoAsync(token, login);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.RetornoVerificacaoServico VerificacaoPeriodicaServico() {
            return base.Channel.VerificacaoPeriodicaServico();
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.RetornoVerificacaoServico> VerificacaoPeriodicaServicoAsync() {
            return base.Channel.VerificacaoPeriodicaServicoAsync();
        }
        
        public void CriarUsuarioExterno(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario) {
            base.Channel.CriarUsuarioExterno(token, usuario);
        }
        
        public System.Threading.Tasks.Task CriarUsuarioExternoAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario) {
            return base.Channel.CriarUsuarioExternoAsync(token, usuario);
        }
        
        public void CriarUsuario(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario, string senha) {
            base.Channel.CriarUsuario(token, usuario, senha);
        }
        
        public System.Threading.Tasks.Task CriarUsuarioAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario, string senha) {
            return base.Channel.CriarUsuarioAsync(token, usuario, senha);
        }
        
        public void AssociarUsuarioAoSistemaPerfil(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario) {
            base.Channel.AssociarUsuarioAoSistemaPerfil(token, usuario);
        }
        
        public System.Threading.Tasks.Task AssociarUsuarioAoSistemaPerfilAsync(string token, INMETRO.CIPP.WEB.ServiceReference1.Usuario usuario) {
            return base.Channel.AssociarUsuarioAoSistemaPerfilAsync(token, usuario);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Usuario BuscarUsuarioExterno(string token, string login) {
            return base.Channel.BuscarUsuarioExterno(token, login);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Usuario> BuscarUsuarioExternoAsync(string token, string login) {
            return base.Channel.BuscarUsuarioExternoAsync(token, login);
        }
        
        public void AtivarDesativarUsuarioExterno(string token, string login, bool ativo) {
            base.Channel.AtivarDesativarUsuarioExterno(token, login, ativo);
        }
        
        public System.Threading.Tasks.Task AtivarDesativarUsuarioExternoAsync(string token, string login, bool ativo) {
            return base.Channel.AtivarDesativarUsuarioExternoAsync(token, login, ativo);
        }
        
        public void AtivarDesativarUsuarioInterno(string token, string login, bool ativo) {
            base.Channel.AtivarDesativarUsuarioInterno(token, login, ativo);
        }
        
        public System.Threading.Tasks.Task AtivarDesativarUsuarioInternoAsync(string token, string login, bool ativo) {
            return base.Channel.AtivarDesativarUsuarioInternoAsync(token, login, ativo);
        }
        
        public INMETRO.CIPP.WEB.ServiceReference1.Perfil[] ObterPerfisSistema(string token) {
            return base.Channel.ObterPerfisSistema(token);
        }
        
        public System.Threading.Tasks.Task<INMETRO.CIPP.WEB.ServiceReference1.Perfil[]> ObterPerfisSistemaAsync(string token) {
            return base.Channel.ObterPerfisSistemaAsync(token);
        }
    }
}
